"""
generators/potcar.py — POTCAR file generator.

Supports uploading an existing POTCAR or creating one by selecting
elements and concatenating per-element POTCAR files from a local directory.
"""

import os

import streamlit as st

from sections.input_generator import render_file_output


# ===========================================================================
# Public entry point
# ===========================================================================

def render_potcar_tab() -> None:
    """Render the POTCAR generator tab."""
    if "potcar_show_save_dialog" not in st.session_state:
        st.session_state.potcar_show_save_dialog = False

    potcar_method = st.radio(
        "Choose generation method:",
        ["Upload POTCAR", "Create POTCAR"],
        horizontal=True,
    )

    handlers = {
        "Upload POTCAR": _potcar_from_upload,
        "Create POTCAR": _potcar_create,
    }
    handler = handlers.get(potcar_method)
    if handler:
        handler()

    # Show preview if content has been generated
    if "potcar_content" in st.session_state:
        render_file_output(st.session_state.potcar_content, "POTCAR", "potcar")


# ===========================================================================
# Upload method
# ===========================================================================

def _potcar_from_upload() -> None:
    """Load POTCAR from an uploaded file."""
    st.markdown("###### Upload Existing POTCAR")
    uploaded_file = st.file_uploader("Choose a POTCAR file", type=None,
                                     accept_multiple_files=False)
    if uploaded_file is not None:
        try:
            file_content = uploaded_file.getvalue().decode("utf-8")
            st.success("File uploaded successfully!")
            if st.button("Use This POTCAR", key="gen_uploaded_potcar"):
                st.session_state.potcar_content = file_content
                st.success("POTCAR loaded successfully!")
                st.rerun()
        except Exception as e:
            st.error(f"Error reading file: {str(e)}")
            st.info("Make sure the file is in valid POTCAR format")


# ===========================================================================
# Create method (concatenate per-element POTCARs)
# ===========================================================================

# Full periodic-table element list for the multi-select widget.
_ALL_ELEMENTS = [
    "H", "He", "Li", "Be", "B", "C", "N", "O", "F", "Ne",
    "Na", "Mg", "Al", "Si", "P", "S", "Cl", "Ar", "K", "Ca",
    "Sc", "Ti", "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn",
    "Ga", "Ge", "As", "Se", "Br", "Kr", "Rb", "Sr", "Y", "Zr",
    "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag", "Cd", "In", "Sn",
    "Sb", "Te", "I", "Xe", "Cs", "Ba", "La", "Ce", "Pr", "Nd",
    "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb",
    "Lu", "Hf", "Ta", "W", "Re", "Os", "Ir", "Pt", "Au", "Hg",
    "Tl", "Pb", "Bi", "Po", "At", "Rn", "Fr", "Ra", "Ac", "Th",
    "Pa", "U", "Np", "Pu", "Am", "Cm", "Bk", "Cf", "Es", "Fm",
    "Md", "No", "Lr",
]


def _potcar_create() -> None:
    """Create POTCAR by selecting elements and a local POTCAR directory."""
    st.markdown("###### Create POTCAR")
    st.info("POTCAR is generated by concatenating individual POTCAR files for each element.")

    if "potcar_path" not in st.session_state:
        st.session_state.potcar_path = ""

    potcar_path = st.text_input(
        "POTCAR Directory Path",
        value=st.session_state.potcar_path,
        placeholder="/path/to/potcars",
    )

    potcar_elements = st.multiselect("Select Elements for POTCAR", _ALL_ELEMENTS)
    functional = st.selectbox("Exchange-Correlation Functional", ["PBE", "LDA", "GGA"])

    st.session_state.potcar_path = potcar_path

    if st.button("Generate POTCAR"):
        if not potcar_elements:
            st.error("Please select at least one element")
            return
        if not potcar_path:
            st.error("Please specify POTCAR directory path")
            return

        _build_potcar(potcar_path, potcar_elements, functional)


def _build_potcar(potcar_path: str, elements: list, functional: str) -> None:
    """
    Read per-element POTCAR files from disk and concatenate them.

    Tries two directory layouts:
      1. <potcar_path>/<functional>/<element>/POTCAR
      2. <potcar_path>/<element>/POTCAR   (fallback)
    """
    potcar_contents = []
    missing_elements = []

    for elem in elements:
        # Primary path: <root>/<functional>/<elem>/POTCAR
        primary = os.path.join(potcar_path, functional, elem, "POTCAR")
        # Fallback path: <root>/<elem>/POTCAR
        fallback = os.path.join(potcar_path, elem, "POTCAR")

        found = False
        for path in (primary, fallback):
            if os.path.exists(path):
                try:
                    with open(path, "r") as f:
                        potcar_contents.append(f.read())
                    found = True
                    break
                except Exception as e:
                    st.warning(f"Could not read {elem} POTCAR: {e}")

        if not found:
            missing_elements.append(elem)

    # Report missing elements with a helpful concatenation command
    if missing_elements:
        st.error(f"POTCAR files not found for: {', '.join(missing_elements)}")
        _show_cat_command(potcar_path, elements, functional)
        return

    if potcar_contents:
        st.session_state.potcar_content = "".join(potcar_contents)
        st.success(f"POTCAR generated with {len(elements)} element(s)!")
    else:
        st.error("No POTCAR files could be read. Please check the path.")
        _show_cat_command(potcar_path, elements, functional)


def _show_cat_command(potcar_path: str, elements: list, functional: str) -> None:
    """Display a shell command the user can run manually to build POTCAR."""
    cmd = "# Command to concatenate POTCAR files:\ncat "
    for elem in elements:
        cmd += f"{potcar_path}/{functional}/{elem}/POTCAR \\\n"
    cmd += "> POTCAR"
    st.code(cmd, language="bash")
